version: '3.1'

services:
  db:
    container_name: pg_database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: postgre
    volumes:
      - C:/Users/I528407/Desktop/test/infile:/infile
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  pg_data: